services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_PASSWORD:-YourPassword123!}
    ports:
      - "${MSSQL_PORT:-1433}:1433"
    restart: unless-stopped
    volumes:
      - ./data/mssql:/var/opt/mssql/data
      - shared_backup_volume:/shared_backup

  backup-tool:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    stdin_open: true
    volumes:
      - ./data_backups:/data/input
      - shared_backup_volume:/shared_backup
      - ./logs:/logs
    environment:
      - MSSQL_SERVER=mssql
      - MSSQL_USER=sa
      - MSSQL_PASSWORD=${MSSQL_PASSWORD:-YourPassword123!}
      - BACKUP_WATCH_DIR=/data/input
      - BACKUP_SHARED_DIR=/shared_backup
      - APP_LOG_LEVEL=INFO
      - TOOL_MODE=monitor
    depends_on:
      - mssql

volumes:
  shared_backup_volume:
